# Generated by Django 5.0.2 on 2024-09-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время обновления')),
                ('flag', models.BooleanField(default=1, verbose_name='Флаг активности')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('func_name', models.CharField(max_length=255)),
                ('lineno', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'db_log',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['time'], name='ind_db_log_time'), models.Index(fields=['level'], name='ind_db_log_level')],
            },
        ),
    ]
