#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --noinput
python manage.py init_admin
python manage.py create_roles

/usr/local/bin/gunicorn mainmodule.asgi:application  -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8001 --chdir=/encar_bot