services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start
    ports:
      - 8000:8000
    volumes:
      - .:/encar_api
    networks:
      - encar_net
    env_file:
      - ./.env/.env.dev

networks:
  encar_net:
    external: true