version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start
    ports:
      - 8000:8000
    volumes:
      - .:/encar_api
    networks:
      - net-for-api
    env_file:
      - ./.env/.env.dev

networks:
  net-for-api:
    external:
      name: encar-net