INSERT INTO encar.inspection_list (car_id, last_id, last_parsing_ts,
                                   car_specification, licence_plate, registration_date,
                                   fuel_id, fuel, warranty_type, model_year, warranty_period,
                                   transmission_id, transmission_type, vin, engine_type, mileage_gauge_status,
                                   mileage, vin_condition, exhaust_gas, tuning, special_history,
                                   change_of_use, color, main_options, recall_target, accident_history,
                                   simple_repair, special_notes, damages_table, details_table, photos,
                                   inspector, informant, inspect_date, special_notes_inspector, inspection_photo_list,
                                   search_run, parser_run, warranty_period_to, warranty_period_from)
    SELECT
        temp.car_id, temp.last_id, temp.last_parsing_ts,
        temp.car_specification, temp.licence_plate,
        temp.registration_date, temp.fuel_id, temp.fuel, temp.warranty_type,
        temp.model_year, temp.warranty_period,
        temp.transmission_id, temp.transmission_type, temp.vin, temp.engine_type, temp.mileage_gauge_status,
        temp.mileage, temp.vin_condition, temp.exhaust_gas, temp.tuning, temp.special_history,
        temp.change_of_use, temp.color, temp.main_options, temp.recall_target, temp.accident_history,
        temp.simple_repair, temp.special_notes, temp.damages_table, temp.details_table, temp.photos,
        temp.inspector, temp.informant, temp.inspect_date, temp.special_notes_inspector, temp.inspection_photo_list,
        temp.search_run, temp.parser_run, temp.warranty_period_to, temp.warranty_period_from
    FROM temp_table as temp
    ON CONFLICT (car_id) DO UPDATE
    SET last_id = excluded.last_id, last_parsing_ts = excluded.last_parsing_ts,
        car_specification = excluded.car_specification,
        licence_plate = excluded.licence_plate, registration_date = excluded.registration_date,
        fuel_id = excluded.fuel_id, fuel = excluded.fuel, warranty_type = excluded.warranty_type,
        model_year = excluded.model_year, warranty_period = excluded.warranty_period,
        transmission_id = excluded.transmission_id, transmission_type = excluded.transmission_type,
        vin = excluded.vin, engine_type = excluded.engine_type,
        mileage_gauge_status = excluded.mileage_gauge_status,
        mileage = excluded.mileage, vin_condition = excluded.vin_condition, exhaust_gas = excluded.exhaust_gas,
        tuning = excluded.tuning, special_history = excluded.special_history, change_of_use = excluded.change_of_use,
        color = excluded.color, main_options = excluded.main_options, recall_target = excluded.recall_target,
        accident_history = excluded.accident_history, simple_repair = excluded.simple_repair,
        special_notes = excluded.special_notes, damages_table = excluded.damages_table,
        details_table = excluded.details_table, photos = excluded.photos, inspector = excluded.inspector,
        informant = excluded.informant, inspect_date = excluded.inspect_date,
        special_notes_inspector = excluded.special_notes_inspector,
        inspection_photo_list = excluded.inspection_photo_list, search_run = excluded.search_run,
        parser_run = excluded.parser_run, warranty_period_to = excluded.warranty_period_to,
        warranty_period_from = excluded.warranty_period_from
