INSERT INTO encar.inspection_list_translated (car_id, last_id, last_parsing_ts,
                                            car_specification, licence_plate, registration_date,
                                            fuel_id, fuel, warranty_type, model_year, warranty_period,
                                            transmission_id, transmission_type, vin, engine_type, mileage_gauge_status,
                                            mileage, vin_condition, exhaust_gas, tuning, special_history,
                                            change_of_use, color, main_options, recall_target, accident_history,
                                            simple_repair, special_notes, damages_table, details_table, photos,
                                            inspector, informant, inspect_date, special_notes_inspector, inspection_photo_list,
                                            search_run, parser_run, warranty_period_to, warranty_period_from,
                                            car_specification_russian, car_specification_english, warranty_type_russian,
                                            warranty_type_english, accident_history_russian, accident_history_english,
                                            simple_repair_russian, simple_repair_english, mileage_gauge_status_russian,
                                            mileage_gauge_status_english, mileage_russian, mileage_english, vin_condition_russian,
                                            vin_condition_english, exhaust_gas_russian, exhaust_gas_english, special_history_russian,
                                            special_history_english, change_of_use_russian, change_of_use_english, color_russian,
                                            color_english, main_options_russian, main_options_english, recall_target_russian,
                                            recall_target_english, damages_table_russian, damages_table_english,
                                            details_table_russian, details_table_english)
    SELECT
        temp.car_id, temp.last_id, temp.last_parsing_ts,
        temp.car_specification, temp.licence_plate,
        temp.registration_date, temp.fuel_id, temp.fuel, temp.warranty_type,
        temp.model_year, temp.warranty_period,
        temp.transmission_id, temp.transmission_type, temp.vin, temp.engine_type, temp.mileage_gauge_status,
        temp.mileage, temp.vin_condition, temp.exhaust_gas, temp.tuning, temp.special_history,
        temp.change_of_use, temp.color, temp.main_options, temp.recall_target, temp.accident_history,
        temp.simple_repair, temp.special_notes, temp.damages_table, temp.details_table, temp.photos,
        temp.inspector, temp.informant, temp.inspect_date, temp.special_notes_inspector, temp.inspection_photo_list,
        temp.search_run, temp.parser_run, temp.warranty_period_to, temp.warranty_period_from,
        temp.car_specification_russian, temp.car_specification_english,temp.warranty_type_russian,
        temp.warranty_type_english, temp.accident_history_russian, temp.accident_history_english,
        temp.simple_repair_russian, temp.simple_repair_english, temp.mileage_gauge_status_russian,
        temp.mileage_gauge_status_english, temp.mileage_russian, temp.mileage_english,temp.vin_condition_russian,
        temp.vin_condition_english, temp.exhaust_gas_russian, temp.exhaust_gas_english, temp.special_history_russian,
        temp.special_history_english, temp.change_of_use_russian, temp.change_of_use_english, temp.color_russian,
        temp.color_english, temp.main_options_russian, temp.main_options_english, temp.recall_target_russian,
        temp.recall_target_english, temp.damages_table_russian, temp.damages_table_english,
        temp.details_table_russian, temp.details_table_english
    FROM temp_table as temp
    ON CONFLICT (car_id) DO UPDATE
    SET last_id = excluded.last_id, last_parsing_ts = excluded.last_parsing_ts,
        car_specification = excluded.car_specification,
        licence_plate = excluded.licence_plate, registration_date = excluded.registration_date,
        fuel_id = excluded.fuel_id, fuel = excluded.fuel, warranty_type = excluded.warranty_type,
        model_year = excluded.model_year, warranty_period = excluded.warranty_period,
        transmission_id = excluded.transmission_id, transmission_type = excluded.transmission_type,
        vin = excluded.vin, engine_type = excluded.engine_type,
        mileage_gauge_status = excluded.mileage_gauge_status,
        mileage = excluded.mileage, vin_condition = excluded.vin_condition, exhaust_gas = excluded.exhaust_gas,
        tuning = excluded.tuning, special_history = excluded.special_history, change_of_use = excluded.change_of_use,
        color = excluded.color, main_options = excluded.main_options, recall_target = excluded.recall_target,
        accident_history = excluded.accident_history, simple_repair = excluded.simple_repair,
        special_notes = excluded.special_notes, damages_table = excluded.damages_table,
        details_table = excluded.details_table, photos = excluded.photos, inspector = excluded.inspector,
        informant = excluded.informant, inspect_date = excluded.inspect_date,
        special_notes_inspector = excluded.special_notes_inspector,
        inspection_photo_list = excluded.inspection_photo_list, search_run = excluded.search_run,
        parser_run = excluded.parser_run, warranty_period_to = excluded.warranty_period_to,
        warranty_period_from = excluded.warranty_period_from,
        car_specification_russian = excluded.car_specification_russian, car_specification_english = excluded.car_specification_english,
        warranty_type_russian = excluded.warranty_type_russian, warranty_type_english = excluded.warranty_type_english,
        accident_history_russian = excluded.accident_history_russian, accident_history_english = excluded.accident_history_english,
        simple_repair_russian = excluded.simple_repair_russian, simple_repair_english = excluded.simple_repair_english,
        mileage_gauge_status_russian = excluded.mileage_gauge_status_russian,
        mileage_gauge_status_english = excluded.mileage_gauge_status_english, mileage_russian = excluded.mileage_russian,
        mileage_english = excluded.mileage_english, vin_condition_russian = excluded.vin_condition_russian,
        vin_condition_english = excluded.vin_condition_english, exhaust_gas_russian = excluded.exhaust_gas_russian,
        exhaust_gas_english = excluded.exhaust_gas_english, special_history_russian = excluded.special_history_russian,
        special_history_english = excluded.special_history_english, change_of_use_russian = excluded.change_of_use_russian,
        change_of_use_english = excluded.change_of_use_english, color_russian = excluded.color_russian,
        color_english = excluded.color_english, main_options_russian = excluded.main_options_russian,
        main_options_english = excluded.main_options_english, recall_target_russian = excluded.recall_target_russian,
        recall_target_english = excluded.recall_target_english, damages_table_russian = excluded.damages_table_russian,
        damages_table_english = excluded.damages_table_english, details_table_russian = excluded.details_table_russian,
        details_table_english = excluded.details_table_english
