#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A mainmodule inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

exec celery -A mainmodule  \
    --broker="${CELERY_BROKER}" \
    flower --loglevel=info --url_prefix=/flower --port=5555 --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"